version: '3'

services:

  db:
    image: postgres:alpine3.18
    container_name: users_db
    restart: always
    ports:
      - "5430:5432"
    networks:
      - custom
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=users


  auth:
    image: users_fastapi
    container_name: users_fastapi
    depends_on:
      - db
    build:
      context: src/auth/
      dockerfile: Dockerfile
    command: 'sh -c "alembic upgrade head && python main.py"'
    ports:
      - 8000:8000
    networks:
      - custom

  gateway:
    image: gateway
    container_name: gateway
    build:
      context: src/gateway/
      dockerfile: Dockerfile
    command: 'sh -c "python main.py"'
    ports:
      - 7000:7000
    networks:
      - custom


networks:
  custom:
    driver: bridge
volumes:
  db-data: