version: '3'

services:

  db:
    image: postgres:alpine3.18
    container_name: cards_db
    restart: always
    ports:
      - "5431:5432"
    networks:
      - custom
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=cards


networks:
  custom:
    driver: bridge
volumes:
  db-data: