version: '3'

services:

  db:
    image: postgres:alpine3.18
    container_name: users_db
    build:
      context: .
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=music